version: "1.0"

services:
  web:
    image: creationduwal/vdf
    container_name: v2s
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
    restart: unless-stopped